name: GitHub-Profile-3D-Contrib

on:
  schedule: # 20:00 UTC == 04:00 GMT+8
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name ganximi
          git config user.email mixiang0601@163.com
          git add -A .
          git commit -m "generated"
          git push
